[filters] 
# processes that are allowed to spawn shells
safe_shell_launchers = [
    "bash", "sh", "zsh", "fish",
    "tmux", "alacritty", "kitty",
    "sshd", "sudo", "su", "login",
    "hyprland", "code"
]

#ignore this one as it is too common
ignored_comms = [
    "cpuUsage.sh"
]